# Generated by Django 3.0.7 on 2020-08-07 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0009_delete_biodata_dict_labels'),
        ('users', '0011_remove_userdetails_dialcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name_engagement', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('template_url_engagement', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('template_price_engagement', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('template_image_engagement', models.ImageField(default='', upload_to='media/engagement/templates/icon')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EngagementCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('bride_first_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('groom_first_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('groom_father', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('groom_mother', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('bride_father', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('bride_mother', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('date_of_engagement', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('time_of_engagement', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('place_of_engagement', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('special_guest_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('guest_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('contact_mobile', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('bride_image', models.ImageField(default='', upload_to='media/engagement/templates/images')),
                ('groom_image', models.ImageField(default='', upload_to='media/engagement/templates/images')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('engagement_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_user_details', to='users.UserDetails')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_language_name', to='languages.Engagement')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_templates', to='engagement_cards.TemplateData')),
            ],
        ),
    ]
