# Generated by Django 4.1.5 on 2023-06-17 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('groom_or_bride', models.IntegerField(choices=[(0, 'GROOM'), (1, 'BRIDE')], default=1)),
                ('bride_first_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('groom_first_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('groom_father', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('groom_mother', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('bride_father', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('bride_mother', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('date_of_engagement', models.DateTimeField(blank=True, default='', null=True)),
                ('time_of_engagement', models.TimeField(blank=True, default='', null=True)),
                ('place_of_engagement', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('special_guest_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('guest_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('contact_mobile', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('bride_image', models.ImageField(default='', upload_to='media/engagement/templates/images')),
                ('groom_image', models.ImageField(default='', upload_to='media/engagement/templates/images')),
                ('engagement_card_status', models.IntegerField(choices=[(1, 'DRAFT'), (2, 'PUCHASED'), (3, 'WATCHED_ADS'), (4, 'DELETED')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name_engagement', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('template_url_engagement', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('template_type_engagement', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('template_price', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('template_image_engagement_icon', models.ImageField(default='', upload_to='media/engagement/templates/icon')),
                ('template_image_engagement', models.ImageField(default='', upload_to='media/engagement/templates/images')),
                ('status', models.IntegerField(choices=[(0, 'ACTIVE'), (1, 'INACTIVE')], default=0)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('template_country_engagement', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='template_country_engagement', to='cities_light.country')),
            ],
        ),
    ]
