# Generated by Django 4.1.5 on 2023-06-17 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('languages', '0001_initial'),
        ('engagement_cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementcard',
            name='engagement_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_user_details', to='users.userdetails'),
        ),
        migrations.AddField(
            model_name='engagementcard',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_language_name', to='languages.engagement'),
        ),
        migrations.AddField(
            model_name='engagementcard',
            name='paid_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engagement_cards.templatedata'),
        ),
        migrations.AddField(
            model_name='engagementcard',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.payment'),
        ),
        migrations.AddField(
            model_name='engagementcard',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_templates', to='engagement_cards.templatedata'),
        ),
    ]
