# Generated by Django 4.1.5 on 2023-03-12 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_payment_payment_status_alter_payment_status'),
        ('engagement_cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementcard',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.payment'),
        ),
    ]
