# Generated by Django 3.0.7 on 2020-08-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement_cards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatedata',
            name='template_image_engagement_icon',
            field=models.ImageField(default='', upload_to='media/engagement/templates/icon'),
        ),
        migrations.AlterField(
            model_name='templatedata',
            name='template_image_engagement',
            field=models.ImageField(default='', upload_to='media/engagement/templates/images'),
        ),
    ]
