# Generated by Django 3.0.7 on 2020-08-08 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0009_add_subregion'),
        ('engagement_cards', '0002_auto_20200808_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatedata',
            name='template_country_engagement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='template_country_engagement', to='cities_light.Country'),
        ),
        migrations.AddField(
            model_name='templatedata',
            name='template_type_engagement',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
