# Generated by Django 4.1.5 on 2023-04-01 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engagement_cards', '0002_engagementcard_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagementcard',
            name='paid_template',
        ),
        migrations.RemoveField(
            model_name='templatedata',
            name='template_price',
        ),
    ]
