# Generated by Django 4.1.5 on 2023-04-01 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engagement_cards', '0003_remove_engagementcard_paid_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementcard',
            name='paid_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engagement_cards.templatedata'),
        ),
        migrations.AddField(
            model_name='templatedata',
            name='template_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
