# Generated by Django 3.0.7 on 2020-08-12 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement_cards', '0003_auto_20200808_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementcard',
            name='engagement_card_status',
            field=models.IntegerField(choices=[(1, 'DRAFT'), (2, 'PUCHASED'), (3, 'WATCHED_ADS'), (4, 'DELETED')], default=1),
        ),
        migrations.AlterField(
            model_name='engagementcard',
            name='date_of_engagement',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
    ]
