# Generated by Django 3.0.7 on 2020-08-12 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement_cards', '0004_auto_20200812_0425'),
    ]

    operations = [
        migrations.AddField(
            model_name='engagementcard',
            name='groom_or_bride',
            field=models.IntegerField(choices=[(0, 'GROOM'), (1, 'BRIDE')], default=1),
        ),
    ]
