# Generated by Django 3.0.7 on 2020-08-12 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement_cards', '0005_engagementcard_groom_or_bride'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatedata',
            name='status',
            field=models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0),
        ),
    ]
