# Generated by Django 3.0.7 on 2020-08-12 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement_cards', '0006_templatedata_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engagementcard',
            name='time_of_engagement',
            field=models.TimeField(blank=True, default='', null=True),
        ),
    ]
