# Generated by Django 3.0.2 on 2020-02-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagename',
            name='language_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
