# Generated by Django 3.0.7 on 2020-07-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_languagename_language_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagename',
            name='biodata_label',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
        migrations.AddField(
            model_name='languagename',
            name='birthday_label',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
        migrations.AddField(
            model_name='languagename',
            name='business_card_label',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
        migrations.AddField(
            model_name='languagename',
            name='engagement_label',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
        migrations.AddField(
            model_name='languagename',
            name='language_abr',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='languagename',
            name='other_label',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
        migrations.AddField(
            model_name='languagename',
            name='resume_label',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
        migrations.AddField(
            model_name='languagename',
            name='wedding_label',
            field=models.TextField(blank=True, default='{}', null=True),
        ),
    ]
