# Generated by Django 3.0.7 on 2020-07-28 09:23

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0004_auto_20200725_0553'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodata',
            name='pickeled_label_name',
            field=picklefield.fields.PickledObjectField(blank=True, editable=False, null=True),
        ),
    ]
