# Generated by Django 3.0.7 on 2020-07-28 09:34

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0005_biodata_pickeled_label_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='biodata_dict_labels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickeled_label_name', picklefield.fields.PickledObjectField(editable=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='pickeled_label_name',
        ),
        migrations.AddField(
            model_name='biodata',
            name='biodata_label_name',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='biodata_pickled_labels', to='languages.biodata_dict_labels'),
        ),
    ]
