# Generated by Django 3.0.7 on 2020-07-28 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0006_auto_20200728_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='biodata_label_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biodata_pickled_labels', to='languages.biodata_dict_labels'),
        ),
    ]
