# Generated by Django 3.0.7 on 2020-07-28 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0007_auto_20200728_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biodata',
            name='biodata_label_name',
        ),
    ]
