# Generated by Django 3.0.7 on 2020-07-28 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0008_remove_biodata_biodata_label_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='biodata_dict_labels',
        ),
    ]
