# Generated by Django 2.2.19 on 2021-03-06 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0010_commonwords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='language',
        ),
        migrations.DeleteModel(
            name='Business',
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
