# Generated by Django 2.2.19 on 2021-03-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0011_auto_20210306_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.TextField(blank=True, default='{}', null=True)),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
