# Generated by Django 2.2.19 on 2021-03-09 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0014_latterhad'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscard',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_languages', to='languages.LanguageName'),
        ),
    ]
