# Generated by Django 2.2.19 on 2021-03-09 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0015_businesscard_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscard',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='business_languages', to='languages.LanguageName'),
        ),
    ]
