# Generated by Django 2.2.19 on 2021-03-10 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0016_auto_20210309_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscard',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_languages', to='languages.LanguageName'),
        ),
    ]
