# Generated by Django 2.2.19 on 2021-03-10 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bussiness_cards', '0005_auto_20210310_0049'),
        ('languages', '0018_business'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessCard',
        ),
    ]
