# Generated by Django 3.0.2 on 2020-05-13 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country_dialcode', '0001_initial'),
        ('users', '0002_mobileotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='dialcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='country_dialcode.Prefix'),
        ),
    ]
