# Generated by Django 3.0.2 on 2020-06-18 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0009_add_subregion'),
        ('users', '0008_auto_20200612_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='country_dialcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_dialcodes', to='cities_light.Country'),
        ),
    ]
