# Generated by Django 4.1.5 on 2023-04-03 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_payment_payment_status_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='verification_failed',
            field=models.BooleanField(default=False),
        ),
    ]
