# Generated by Django 4.1.5 on 2023-06-17 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('languages', '0001_initial'),
        ('biodata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodata',
            name='biodata_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biodata_user_details', to='users.userdetails'),
        ),
        migrations.AddField(
            model_name='biodata',
            name='language_name',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biodata_language_name', to='languages.biodata'),
        ),
        migrations.AddField(
            model_name='biodata',
            name='paid_template',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_biodata_template', to='biodata.templatedata'),
        ),
        migrations.AddField(
            model_name='biodata',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biodata_payment', to='users.payment'),
        ),
        migrations.AddField(
            model_name='biodata',
            name='template',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biodata_template', to='biodata.templatedata'),
        ),
    ]
