# Generated by Django 3.0.2 on 2020-02-04 04:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0002_auto_20200204_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodata',
            name='template',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biodata_template', to='biodata.TemplateData'),
        ),
    ]
