# Generated by Django 3.0.2 on 2020-02-04 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0005_remove_biodata_template'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemplateData',
        ),
        migrations.RemoveField(
            model_name='biodata',
            name='diet',
        ),
    ]
