# Generated by Django 3.0.2 on 2020-02-04 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0006_auto_20200204_0516'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('template_url', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('template_price', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='biodata',
            name='diet',
            field=models.IntegerField(choices=[(0, ''), (1, 'Vegetarian'), (2, 'Non-Vegetarian'), (3, 'Ovo Vegetarian'), (4, 'Vegan'), (5, 'Lacto Vegetarians'), (6, 'Lacto-Ovo Vegetarians')], default=0),
        ),
    ]
