# Generated by Django 3.0.2 on 2020-02-04 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0007_auto_20200204_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodata',
            name='template',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biodata_template', to='biodata.TemplateData'),
        ),
    ]
