# Generated by Django 3.0.2 on 2020-06-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0011_auto_20200612_0723'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodata',
            name='completion_year',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='biodata',
            name='institute',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='biodata',
            name='qualification',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
