# Generated by Django 3.0.2 on 2020-06-18 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0012_auto_20200613_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodataimage',
            name='image',
            field=models.ImageField(default='', upload_to='media/biodata/templates/images'),
        ),
        migrations.AlterField(
            model_name='templatedata',
            name='template_price',
            field=models.ImageField(default='', upload_to='media/biodata/templates/icon'),
        ),
    ]
