# Generated by Django 3.0.2 on 2020-06-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0013_auto_20200618_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatedata',
            name='template_image',
            field=models.ImageField(default='', upload_to='media/biodata/templates/icon'),
        ),
        migrations.AlterField(
            model_name='templatedata',
            name='template_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
