# Generated by Django 3.0.7 on 2020-06-27 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0014_auto_20200618_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='about_myself',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='partner_preference',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
