# Generated by Django 3.0.7 on 2020-07-02 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0017_auto_20200701_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelname',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='labelname',
            name='contact',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='labelname',
            name='details',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='labelname',
            name='education',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='labelname',
            name='family',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='labelname',
            name='information',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='labelname',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='labelname',
            name='personal',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
