# Generated by Django 3.0.7 on 2020-07-02 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0018_auto_20200702_0331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labelname',
            old_name='details',
            new_name='about',
        ),
        migrations.AddField(
            model_name='labelname',
            name='detail',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='labelname',
            name='myself',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='labelname',
            name='partner',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='labelname',
            name='preference',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
