# Generated by Django 3.0.7 on 2020-07-02 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0019_auto_20200702_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='labelname',
            name='word_and',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='labelname',
            name='year',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
