# Generated by Django 3.0.7 on 2020-07-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0020_auto_20200702_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodata',
            name='diet_choice',
            field=models.IntegerField(choices=[(0, ''), (1, 'Vegetarian'), (2, 'Non-Vegetarian'), (3, 'Ovo Vegetarian'), (4, 'Vegan'), (5, 'Lacto Vegetarians'), (6, 'Lacto-Ovo Vegetarians')], default=0),
        ),
        migrations.AlterField(
            model_name='biodata',
            name='diet',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
