# Generated by Django 3.0.7 on 2020-08-01 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0021_auto_20200728_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='language_name',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biodata_language_name', to='biodata.LanguageName'),
        ),
    ]
