# Generated by Django 3.0.7 on 2020-08-01 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0009_delete_biodata_dict_labels'),
        ('biodata', '0022_auto_20200801_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biodata',
            name='language_name',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biodata_language_name', to='languages.Biodata'),
        ),
    ]
