# Generated by Django 2.2.3 on 2021-04-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0025_auto_20210306_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatedata',
            name='template_icon_image',
            field=models.ImageField(default='', upload_to='media/biodata/templates/icon'),
        ),
    ]
