# Generated by Django 4.1.5 on 2023-01-14 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_payment'),
        ('biodata', '0026_templatedata_template_icon_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodata',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='biodata_payment', to='users.payment'),
        ),
    ]
