# Generated by Django 4.1.5 on 2023-01-30 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biodata', '0027_biodata_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='biodata',
            name='paid_template',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paid_biodata_template', to='biodata.templatedata'),
        ),
    ]
