# Generated by Django 2.2.19 on 2021-03-06 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0014_latterhad'),
        ('users', '0012_auto_20210306_1522'),
        ('cities_light', '0009_add_subregion'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name_latter_had', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('template_url_latter_had', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('template_type_latter_had', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('template_price_latter_had', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('template_image_latter_had_icon', models.ImageField(default='', upload_to='media/latter_had/templates/icon')),
                ('template_image_latter_had', models.ImageField(default='', upload_to='media/latter_had/templates/images')),
                ('status', models.IntegerField(choices=[(0, 'ACTIVE'), (1, 'INACTIVE')], default=0)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('template_country_latter_had', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='template_country_latter_had', to='cities_light.Country')),
            ],
        ),
        migrations.CreateModel(
            name='LatterHadCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('company_name', models.CharField(default='', max_length=100)),
                ('established_date', models.CharField(default='', max_length=100)),
                ('Address', models.CharField(default='', max_length=100)),
                ('contact', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('linkedin', models.CharField(default='', max_length=100)),
                ('instagram', models.CharField(default='', max_length=100)),
                ('facebook', models.CharField(default='', max_length=100)),
                ('twitter', models.CharField(default='', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_language_name', to='languages.LatterHad')),
                ('latter_had_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latter_had_user_details', to='users.UserDetails')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latter_had_templates', to='latter_had.TemplateData')),
            ],
        ),
    ]
