# Generated by Django 4.1.5 on 2023-06-17 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('latter_had', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='latterhadcard',
            name='latterhad_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='latterhad_user_details', to='users.userdetails'),
        ),
        migrations.AddField(
            model_name='latterhadcard',
            name='paid_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='latter_had.latterhadtemplatedata'),
        ),
        migrations.AddField(
            model_name='latterhadcard',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.payment'),
        ),
        migrations.AddField(
            model_name='latterhadcard',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latterhad_templates', to='latter_had.latterhadtemplatedata'),
        ),
    ]
