# Generated by Django 2.2.19 on 2021-03-07 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latter_had', '0002_auto_20210307_0340'),
    ]

    operations = [
        migrations.AddField(
            model_name='latterhadcard',
            name='latter_had_card_status',
            field=models.IntegerField(choices=[(1, 'DRAFT'), (2, 'PUCHASED'), (3, 'WATCHED_ADS'), (4, 'DELETED')], default=1),
        ),
    ]
