# Generated by Django 2.2.19 on 2021-03-07 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('latter_had', '0003_latterhadcard_latter_had_card_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='latterhadcard',
            old_name='latter_had_card_status',
            new_name='latterhad_card_status',
        ),
    ]
