# Generated by Django 2.2.19 on 2021-03-07 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210306_1522'),
        ('cities_light', '0009_add_subregion'),
        ('latter_had', '0004_auto_20210307_0557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='latterhadtemplatedata',
            old_name='template_name_latter_had',
            new_name='template_name_latterhad',
        ),
        migrations.RenameField(
            model_name='latterhadtemplatedata',
            old_name='template_price_latter_had',
            new_name='template_price_latterhad',
        ),
        migrations.RenameField(
            model_name='latterhadtemplatedata',
            old_name='template_type_latter_had',
            new_name='template_type_latterhad',
        ),
        migrations.RenameField(
            model_name='latterhadtemplatedata',
            old_name='template_url_latter_had',
            new_name='template_url_latterhad',
        ),
        migrations.RemoveField(
            model_name='latterhadcard',
            name='latter_had_user',
        ),
        migrations.RemoveField(
            model_name='latterhadtemplatedata',
            name='template_country_latter_had',
        ),
        migrations.RemoveField(
            model_name='latterhadtemplatedata',
            name='template_image_latter_had',
        ),
        migrations.RemoveField(
            model_name='latterhadtemplatedata',
            name='template_image_latter_had_icon',
        ),
        migrations.AddField(
            model_name='latterhadcard',
            name='latterhad_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='latterhad_user_details', to='users.UserDetails'),
        ),
        migrations.AddField(
            model_name='latterhadtemplatedata',
            name='template_country_latterhad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='template_country_latterhad', to='cities_light.Country'),
        ),
        migrations.AddField(
            model_name='latterhadtemplatedata',
            name='template_image_latterhad',
            field=models.ImageField(default='', upload_to='media/latterhad/templates/images'),
        ),
        migrations.AddField(
            model_name='latterhadtemplatedata',
            name='template_image_latterhad_icon',
            field=models.ImageField(default='', upload_to='media/latterhad/templates/icon'),
        ),
        migrations.AlterField(
            model_name='latterhadcard',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='latterhad_templates', to='latter_had.LatterHadTemplateData'),
        ),
    ]
