# Generated by Django 2.2.19 on 2021-03-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latter_had', '0005_auto_20210307_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='latterhadcard',
            name='image',
            field=models.ImageField(default='', upload_to='media/resume/templates/images'),
        ),
    ]
