# Generated by Django 2.2.19 on 2021-03-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('latter_had', '0006_latterhadcard_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latterhadcard',
            name='image',
        ),
        migrations.AddField(
            model_name='latterhadcard',
            name='logo',
            field=models.ImageField(default='', upload_to='media/resume/templates/images'),
        ),
    ]
