# Generated by Django 2.2.19 on 2021-03-28 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('latter_had', '0007_auto_20210328_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='latterhadcard',
            old_name='Address',
            new_name='address',
        ),
    ]
