# Generated by Django 2.2.19 on 2021-03-28 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('latter_had', '0009_latterhadcard_website'),
    ]

    operations = [
        migrations.RenameField(
            model_name='latterhadcard',
            old_name='instagram',
            new_name='other_social_id',
        ),
    ]
