# Generated by Django 4.1.5 on 2023-03-11 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_payment_payment_status_alter_payment_status'),
        ('latter_had', '0010_auto_20210328_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='latterhadcard',
            name='paid_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='latter_had.latterhadtemplatedata'),
        ),
        migrations.AddField(
            model_name='latterhadcard',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.payment'),
        ),
    ]
