# Generated by Django 4.1.5 on 2023-03-11 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('latter_had', '0011_latterhadcard_paid_template_latterhadcard_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='latterhadtemplatedata',
            old_name='template_price_latterhad',
            new_name='template_price',
        ),
    ]
