# Generated by Django 4.1.5 on 2023-06-17 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeTemplateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name_resume', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('template_url_resume', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('template_type_resume', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('template_price', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('template_image_resume_icon', models.ImageField(default='', upload_to='media/resume/templates/icon')),
                ('template_image_resume', models.ImageField(default='', upload_to='media/resume/templates/images')),
                ('status', models.IntegerField(choices=[(0, 'ACTIVE'), (1, 'INACTIVE')], default=0)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('template_country_resume', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='template_country_resume', to='cities_light.country')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('father', models.CharField(default='', max_length=100)),
                ('mother', models.CharField(default='', max_length=100)),
                ('date_of_birth', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('contact', models.CharField(default='', max_length=100)),
                ('gmail', models.CharField(default='', max_length=100)),
                ('linkedin', models.CharField(default='', max_length=100)),
                ('skype', models.CharField(default='', max_length=100)),
                ('facebook', models.CharField(default='', max_length=100)),
                ('twitter', models.CharField(default='', max_length=100)),
                ('instagram', models.CharField(default='', max_length=100)),
                ('social_account', models.CharField(default='', max_length=100)),
                ('profession', models.CharField(default='', max_length=100)),
                ('skills', models.CharField(default='', max_length=100)),
                ('about_profession', models.CharField(default='', max_length=300)),
                ('highest_qualification', models.CharField(default='', max_length=100)),
                ('institute', models.CharField(default='', max_length=100)),
                ('pass_out_year', models.CharField(default='', max_length=100)),
                ('organization', models.CharField(default='', max_length=100)),
                ('languages', models.CharField(default='', max_length=100)),
                ('work_experience1', models.TextField(blank=True, null=True)),
                ('work_experience2', models.TextField(blank=True, null=True)),
                ('work_experience3', models.TextField(blank=True, null=True)),
                ('work_experience4', models.TextField(blank=True, null=True)),
                ('work_experience5', models.TextField(blank=True, null=True)),
                ('work_experience6', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='', upload_to='media/resume/templates/images')),
                ('resume_card_status', models.IntegerField(choices=[(1, 'DRAFT'), (2, 'PUCHASED'), (3, 'WATCHED_ADS'), (4, 'DELETED')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_language_name', to='languages.resume')),
                ('paid_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resume.resumetemplatedata')),
            ],
        ),
    ]
