# Generated by Django 2.2.19 on 2021-03-06 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0009_add_subregion'),
        ('users', '0012_auto_20210306_1522'),
        ('languages', '0014_latterhad'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name_resume', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('template_url_resume', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('template_type_resume', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('template_price_resume', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('template_image_resume_icon', models.ImageField(default='', upload_to='media/resume/templates/icon')),
                ('template_image_resume', models.ImageField(default='', upload_to='media/resume/templates/images')),
                ('status', models.IntegerField(choices=[(0, 'ACTIVE'), (1, 'INACTIVE')], default=0)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('template_country_resume', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='template_country_resume', to='cities_light.Country')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('name', models.CharField(default='', max_length=100)),
                ('date_of_birth', models.CharField(default='', max_length=100)),
                ('Address', models.CharField(default='', max_length=100)),
                ('contact', models.CharField(default='', max_length=100)),
                ('gmail', models.CharField(default='', max_length=100)),
                ('linkedin', models.CharField(default='', max_length=100)),
                ('skype', models.CharField(default='', max_length=100)),
                ('facebook', models.CharField(default='', max_length=100)),
                ('twitter', models.CharField(default='', max_length=100)),
                ('instagram', models.CharField(default='', max_length=100)),
                ('other_email', models.CharField(default='', max_length=100)),
                ('professional', models.CharField(default='', max_length=100)),
                ('skills', models.CharField(default='', max_length=100)),
                ('about_professional', models.CharField(default='', max_length=100)),
                ('highest_qualification', models.CharField(default='', max_length=100)),
                ('college_school', models.CharField(default='', max_length=100)),
                ('pass_out_year', models.CharField(default='', max_length=100)),
                ('organizations', models.CharField(default='', max_length=100)),
                ('languages', models.CharField(default='', max_length=100)),
                ('work_experience1', models.CharField(default='', max_length=100)),
                ('work_experience1_date', models.CharField(default='', max_length=100)),
                ('work_experience1_details', models.CharField(default='', max_length=100)),
                ('work_experience1_city', models.CharField(default='', max_length=100)),
                ('work_experience1_country', models.CharField(default='', max_length=100)),
                ('work_experience2', models.CharField(default='', max_length=100)),
                ('work_experience2_date', models.CharField(default='', max_length=100)),
                ('work_experience2_details', models.CharField(default='', max_length=100)),
                ('work_experience2_city', models.CharField(default='', max_length=100)),
                ('work_experience2_country', models.CharField(default='', max_length=100)),
                ('work_experience3', models.CharField(default='', max_length=100)),
                ('work_experience3_date', models.CharField(default='', max_length=100)),
                ('work_experience3_details', models.CharField(default='', max_length=100)),
                ('work_experience3_city', models.CharField(default='', max_length=100)),
                ('work_experience3_country', models.CharField(default='', max_length=100)),
                ('work_experience4', models.CharField(default='', max_length=100)),
                ('work_experience4_date', models.CharField(default='', max_length=100)),
                ('work_experience4_details', models.CharField(default='', max_length=100)),
                ('work_experience4_city', models.CharField(default='', max_length=100)),
                ('work_experience4_country', models.CharField(default='', max_length=100)),
                ('work_experience5', models.CharField(default='', max_length=100)),
                ('work_experience5_date', models.CharField(default='', max_length=100)),
                ('work_experience5_details', models.CharField(default='', max_length=100)),
                ('work_experience5_city', models.CharField(default='', max_length=100)),
                ('work_experience5_country', models.CharField(default='', max_length=100)),
                ('work_experience6', models.CharField(default='', max_length=100)),
                ('work_experience6_date', models.CharField(default='', max_length=100)),
                ('work_experience6_details', models.CharField(default='', max_length=100)),
                ('work_experience6_city', models.CharField(default='', max_length=100)),
                ('work_experience6_country', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(default='', upload_to='media/resume/templates/images')),
                ('resume_card_status', models.IntegerField(choices=[(1, 'DRAFT'), (2, 'PUCHASED'), (3, 'WATCHED_ADS'), (4, 'DELETED')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_language_name', to='languages.Resume')),
                ('resume_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_user_details', to='users.UserDetails')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_templates', to='resume.TemplateData')),
            ],
        ),
    ]
