# Generated by Django 4.1.5 on 2023-06-17 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumecard',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.payment'),
        ),
        migrations.AddField(
            model_name='resumecard',
            name='resume_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_user_details', to='users.userdetails'),
        ),
        migrations.AddField(
            model_name='resumecard',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_templates', to='resume.resumetemplatedata'),
        ),
    ]
