# Generated by Django 2.2.19 on 2021-03-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20210307_0342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumecard',
            old_name='college_school',
            new_name='father',
        ),
        migrations.RenameField(
            model_name='resumecard',
            old_name='other_email',
            new_name='institute',
        ),
        migrations.AddField(
            model_name='resumecard',
            name='mother',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='resumecard',
            name='social_account',
            field=models.CharField(default='', max_length=100),
        ),
    ]
