# Generated by Django 2.2.19 on 2021-03-23 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20210323_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumecard',
            old_name='professional',
            new_name='profession',
        ),
    ]
