# Generated by Django 2.2.19 on 2021-03-23 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20210323_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumecard',
            old_name='about_professional',
            new_name='about_profession',
        ),
    ]
