# Generated by Django 2.2.19 on 2021-03-27 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_auto_20210324_0305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumecard',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='resumecard',
            old_name='organizations',
            new_name='organization',
        ),
    ]
