# Generated by Django 2.2.3 on 2021-05-26 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_auto_20210327_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumecard',
            name='work_experience_city1',
        ),
        migrations.RemoveField(
            model_name='resumecard',
            name='work_experience_city2',
        ),
        migrations.RemoveField(
            model_name='resumecard',
            name='work_experience_city3',
        ),
        migrations.RemoveField(
            model_name='resumecard',
            name='work_experience_city4',
        ),
        migrations.RemoveField(
            model_name='resumecard',
            name='work_experience_city5',
        ),
        migrations.RemoveField(
            model_name='resumecard',
            name='work_experience_city6',
        ),
        migrations.RemoveField(
            model_name='resumecard',
            name='work_experience_country1',
        ),
        migrations.RemoveField(
            model_name='resumecard',
            name='work_experience_country2',
        ),
        migrations.RemoveField(
            model_name='resumecard',
            name='work_experience_country3',
        ),
        migrations.RemoveField(
            model_name='resumecard',
            name='work_experience_country4',
        ),
        migrations.RemoveField(
            model_name='resumecard',
            name='work_experience_country5',
        ),
        migrations.RemoveField(
            model_name='resumecard',
            name='work_experience_country6',
        ),
        migrations.RemoveField(
            model_name='resumecard',
            name='work_experience_date1',
        ),
        migrations.RemoveField(
            model_name='resumecard',
            name='work_experience_date2',
        ),
        migrations.RemoveField(
            model_name='resumecard',
            name='work_experience_date3',
        ),
        migrations.RemoveField(
            model_name='resumecard',
            name='work_experience_date4',
        ),
        migrations.RemoveField(
            model_name='resumecard',
            name='work_experience_date5',
        ),
        migrations.RemoveField(
            model_name='resumecard',
            name='work_experience_date6',
        ),
        migrations.RemoveField(
            model_name='resumecard',
            name='work_experience_details1',
        ),
        migrations.RemoveField(
            model_name='resumecard',
            name='work_experience_details2',
        ),
        migrations.RemoveField(
            model_name='resumecard',
            name='work_experience_details3',
        ),
        migrations.RemoveField(
            model_name='resumecard',
            name='work_experience_details4',
        ),
        migrations.RemoveField(
            model_name='resumecard',
            name='work_experience_details5',
        ),
        migrations.RemoveField(
            model_name='resumecard',
            name='work_experience_details6',
        ),
        migrations.AlterField(
            model_name='resumecard',
            name='about_profession',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='resumecard',
            name='work_experience1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='resumecard',
            name='work_experience2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='resumecard',
            name='work_experience3',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='resumecard',
            name='work_experience4',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='resumecard',
            name='work_experience5',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='resumecard',
            name='work_experience6',
            field=models.CharField(default='', max_length=200),
        ),
    ]
