# Generated by Django 4.1.5 on 2023-03-11 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_resumecard_paid_template_resumecard_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resumetemplatedata',
            old_name='template_price_resume',
            new_name='template_price',
        ),
    ]
