# Generated by Django 4.1.5 on 2023-04-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_rename_template_price_resume_resumetemplatedata_template_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumecard',
            name='work_experience1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resumecard',
            name='work_experience2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resumecard',
            name='work_experience3',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resumecard',
            name='work_experience4',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resumecard',
            name='work_experience5',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resumecard',
            name='work_experience6',
            field=models.TextField(blank=True, null=True),
        ),
    ]
