# Generated by Django 2.2.19 on 2021-03-07 03:41

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('cities_light', '0009_add_subregion'),
        ('bussiness_cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TemplateData',
            new_name='BusinessTemplateData',
        ),
    ]
