# Generated by Django 2.2.19 on 2021-03-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussiness_cards', '0003_businesscard_business_card_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesscard',
            old_name='facebook',
            new_name='ceo',
        ),
        migrations.RenameField(
            model_name='businesscard',
            old_name='instagram',
            new_name='founder',
        ),
        migrations.RenameField(
            model_name='businesscard',
            old_name='linkedin',
            new_name='social_id1',
        ),
        migrations.RenameField(
            model_name='businesscard',
            old_name='twitter',
            new_name='social_id2',
        ),
        migrations.AddField(
            model_name='businesscard',
            name='telepone',
            field=models.CharField(default='', max_length=100),
        ),
    ]
