# Generated by Django 2.2.19 on 2021-03-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussiness_cards', '0006_businesscard_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscard',
            name='profession',
            field=models.CharField(default='', max_length=100),
        ),
    ]
