# Generated by Django 2.2.19 on 2021-03-12 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussiness_cards', '0007_businesscard_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscard',
            name='logo',
            field=models.ImageField(default='', upload_to='media/business/templates/logo'),
        ),
    ]
