# Generated by Django 2.2.3 on 2021-05-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussiness_cards', '0008_businesscard_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesscard',
            name='company_tagline',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='businesscard',
            name='qrcode',
            field=models.ImageField(default='', upload_to='media/business/templates/qrcode'),
        ),
    ]
