# Generated by Django 2.2.3 on 2021-05-16 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bussiness_cards', '0009_auto_20210516_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesscard',
            old_name='Address',
            new_name='address',
        ),
    ]
