# Generated by Django 2.2.3 on 2021-05-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bussiness_cards', '0010_auto_20210516_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesscard',
            name='qrcode',
            field=models.CharField(default='', max_length=100),
        ),
    ]
