# Generated by Django 4.1.5 on 2023-03-11 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bussiness_cards', '0012_businesscard_paid_template_businesscard_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesstemplatedata',
            old_name='template_price_business',
            new_name='template_price',
        ),
    ]
