# Generated by Django 3.0.7 on 2020-09-18 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0009_delete_biodata_dict_labels'),
        ('users', '0011_remove_userdetails_dialcode'),
        ('cities_light', '0009_add_subregion'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeddingTemplateData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name_wedding', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('template_url_wedding', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('template_type_wedding', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('template_price_wedding', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('template_image_wedding_icon', models.ImageField(default='', upload_to='media/wedding/templates/icon')),
                ('template_image_wedding', models.ImageField(default='', upload_to='media/wedding/templates/images')),
                ('status', models.IntegerField(choices=[(0, 'Active'), (1, 'Inactive')], default=0)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('template_country_wedding', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='template_country_wedding', to='cities_light.Country')),
                ('template_language_wedding', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='template_language_wedding', to='languages.LanguageName')),
            ],
        ),
        migrations.CreateModel(
            name='WeddingCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('groom_or_bride', models.IntegerField(choices=[(0, 'GROOM'), (1, 'BRIDE')], default=1)),
                ('bride_first_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('bride_last_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('groom_first_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('groom_last_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('groom_father', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('groom_mother', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('bride_father', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('bride_mother', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('date_of_wedding', models.DateTimeField(blank=True, default='', null=True)),
                ('time_of_wedding', models.TimeField(blank=True, default='', null=True)),
                ('place_of_wedding', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('special_guest_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('guest_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('contact_mobile', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('bride_image', models.ImageField(default='', upload_to='media/wedding/templates/images')),
                ('groom_image', models.ImageField(default='', upload_to='media/wedding/templates/images')),
                ('wedding_card_status', models.IntegerField(choices=[(1, 'DRAFT'), (2, 'PUCHASED'), (3, 'WATCHED_ADS'), (4, 'DELETED')], default=1)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_language_name', to='languages.Wedding')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wedding_templates', to='wedding_cards.WeddingTemplateData')),
                ('wedding_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wedding_user_details', to='users.UserDetails')),
            ],
        ),
    ]
