# Generated by Django 2.2.3 on 2021-02-06 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weddingcard',
            old_name='bride_main_relatives',
            new_name='bride_main_relative',
        ),
        migrations.RenameField(
            model_name='weddingcard',
            old_name='bride_sibling_relatives',
            new_name='bride_sibling_relative',
        ),
        migrations.RenameField(
            model_name='weddingcard',
            old_name='groom_main_relatives',
            new_name='groom_main_relative',
        ),
        migrations.RenameField(
            model_name='weddingcard',
            old_name='groom_sibling_relatives',
            new_name='groom_sibling_relative',
        ),
    ]
