# Generated by Django 2.2.3 on 2021-02-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_cards', '0002_auto_20210206_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddingcard',
            name='function_date1',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='weddingcard',
            name='function_date2',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='weddingcard',
            name='function_date3',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='weddingcard',
            name='function_date4',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='weddingcard',
            name='function_date5',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='weddingcard',
            name='function_name1',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='weddingcard',
            name='function_name2',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='weddingcard',
            name='function_name3',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='weddingcard',
            name='function_name4',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='weddingcard',
            name='function_name5',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='weddingcard',
            name='wedding_image1',
            field=models.ImageField(default='', upload_to='media/wedding/templates/images'),
        ),
        migrations.AddField(
            model_name='weddingcard',
            name='wedding_image2',
            field=models.ImageField(default='', upload_to='media/wedding/templates/images'),
        ),
        migrations.AddField(
            model_name='weddingcard',
            name='wedding_image3',
            field=models.ImageField(default='', upload_to='media/wedding/templates/images'),
        ),
        migrations.AddField(
            model_name='weddingcard',
            name='wedding_image4',
            field=models.ImageField(default='', upload_to='media/wedding/templates/images'),
        ),
        migrations.AlterField(
            model_name='weddingcard',
            name='date_of_wedding',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='weddingcard',
            name='time_of_wedding',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
