# Generated by Django 2.2.3 on 2021-02-14 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0009_delete_biodata_dict_labels'),
        ('wedding_cards', '0003_auto_20210208_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddingcard',
            name='function_date6',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='weddingcard',
            name='function_name6',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='weddingcard',
            name='function_place1',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='weddingcard',
            name='function_place2',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='weddingcard',
            name='function_place3',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='weddingcard',
            name='function_place4',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='weddingcard',
            name='function_place5',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='weddingcard',
            name='function_place6',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='weddingtemplatedata',
            name='card_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='card_language', to='languages.Wedding'),
        ),
    ]
