# Generated by Django 2.2.3 on 2021-02-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_cards', '0005_weddingtemplatedata_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weddingtemplatedata',
            name='page',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
