# Generated by Django 2.2.3 on 2021-02-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_cards', '0006_auto_20210214_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddingcard',
            name='courteous_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='weddingcard',
            name='inauspicious_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
