# Generated by Django 2.2.3 on 2021-02-16 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_cards', '0007_auto_20210214_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weddingcard',
            old_name='inauspicious_name',
            new_name='auspicious_name',
        ),
    ]
