# Generated by Django 2.2.3 on 2021-02-16 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_cards', '0008_auto_20210216_0233'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weddingcard',
            old_name='auspicious_name',
            new_name='auspicious_fucntion',
        ),
    ]
