# Generated by Django 2.2.19 on 2021-03-06 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_cards', '0009_auto_20210216_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weddingtemplatedata',
            name='status',
            field=models.IntegerField(choices=[(0, 'ACTIVE'), (1, 'INACTIVE')], default=0),
        ),
    ]
