# Generated by Django 2.2.3 on 2021-05-02 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0019_delete_businesscard'),
        ('wedding_cards', '0010_auto_20210306_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(default='', upload_to='media/wedding/templates/html/images')),
                ('image2', models.ImageField(default='', upload_to='media/wedding/templates/html/images')),
                ('image3', models.ImageField(default='', upload_to='media/wedding/templates/html/images')),
                ('image4', models.ImageField(default='', upload_to='media/wedding/templates/html/images')),
                ('image5', models.ImageField(default='', upload_to='media/wedding/templates/html/images')),
                ('image6', models.ImageField(default='', upload_to='media/wedding/templates/html/images')),
                ('image7', models.ImageField(default='', upload_to='media/wedding/templates/html/images')),
                ('image8', models.ImageField(default='', upload_to='media/wedding/templates/html/images')),
                ('image9', models.ImageField(default='', upload_to='media/wedding/templates/html/images')),
                ('image10', models.ImageField(default='', upload_to='media/wedding/templates/html/images')),
                ('image11', models.ImageField(default='', upload_to='media/wedding/templates/html/images')),
                ('image12', models.ImageField(default='', upload_to='media/wedding/templates/html/images')),
                ('image13', models.ImageField(default='', upload_to='media/wedding/templates/html/images')),
                ('image14', models.ImageField(default='', upload_to='media/wedding/templates/html/images')),
                ('image15', models.ImageField(default='', upload_to='media/wedding/templates/html/images')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_html_language_name', to='languages.Wedding')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wedding_template_html_image', to='wedding_cards.WeddingTemplateData')),
            ],
        ),
    ]
