# Generated by Django 2.2.3 on 2021-05-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_cards', '0011_templateimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templateimage',
            name='image1',
            field=models.ImageField(null=True, upload_to='media/wedding/templates/html/images'),
        ),
        migrations.AlterField(
            model_name='templateimage',
            name='image10',
            field=models.ImageField(null=True, upload_to='media/wedding/templates/html/images'),
        ),
        migrations.AlterField(
            model_name='templateimage',
            name='image11',
            field=models.ImageField(null=True, upload_to='media/wedding/templates/html/images'),
        ),
        migrations.AlterField(
            model_name='templateimage',
            name='image12',
            field=models.ImageField(null=True, upload_to='media/wedding/templates/html/images'),
        ),
        migrations.AlterField(
            model_name='templateimage',
            name='image13',
            field=models.ImageField(null=True, upload_to='media/wedding/templates/html/images'),
        ),
        migrations.AlterField(
            model_name='templateimage',
            name='image14',
            field=models.ImageField(null=True, upload_to='media/wedding/templates/html/images'),
        ),
        migrations.AlterField(
            model_name='templateimage',
            name='image15',
            field=models.ImageField(null=True, upload_to='media/wedding/templates/html/images'),
        ),
        migrations.AlterField(
            model_name='templateimage',
            name='image2',
            field=models.ImageField(null=True, upload_to='media/wedding/templates/html/images'),
        ),
        migrations.AlterField(
            model_name='templateimage',
            name='image3',
            field=models.ImageField(null=True, upload_to='media/wedding/templates/html/images'),
        ),
        migrations.AlterField(
            model_name='templateimage',
            name='image4',
            field=models.ImageField(null=True, upload_to='media/wedding/templates/html/images'),
        ),
        migrations.AlterField(
            model_name='templateimage',
            name='image5',
            field=models.ImageField(null=True, upload_to='media/wedding/templates/html/images'),
        ),
        migrations.AlterField(
            model_name='templateimage',
            name='image6',
            field=models.ImageField(null=True, upload_to='media/wedding/templates/html/images'),
        ),
        migrations.AlterField(
            model_name='templateimage',
            name='image7',
            field=models.ImageField(null=True, upload_to='media/wedding/templates/html/images'),
        ),
        migrations.AlterField(
            model_name='templateimage',
            name='image8',
            field=models.ImageField(null=True, upload_to='media/wedding/templates/html/images'),
        ),
        migrations.AlterField(
            model_name='templateimage',
            name='image9',
            field=models.ImageField(null=True, upload_to='media/wedding/templates/html/images'),
        ),
    ]
