# Generated by Django 2.2.3 on 2021-05-05 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_cards', '0013_auto_20210502_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddingcard',
            name='close_relatives_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
