# Generated by Django 4.1.5 on 2023-03-11 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wedding_cards', '0015_weddingcard_paid_template_weddingcard_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weddingtemplatedata',
            old_name='template_price_wedding',
            new_name='template_price',
        ),
    ]
