name: Deploy Django to DigitalOcean

on:
  push:
    branches:
      - master  # Replace with your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Match your Django version

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Deploy to DigitalOcean
      run: |
        # Save the SSH private key and set the correct permissions
        echo "$SSH_PRIVATE_KEY" > /tmp/private_key && chmod 600 /tmp/private_key

        # Start the SSH session and run all commands within the session
        ssh -i /tmp/private_key -o StrictHostKeyChecking=no root@139.59.88.123 << 'EOF'
        cd /home/CardsMaker
        git pull origin main
        source venv/bin/activate
        pip3 install --upgrade pip setuptools wheel
        sudo apt update && sudo apt install -y build-essential python3-dev
        python manage.py migrate
        python manage.py collectstatic --noinput
        systemctl restart gunicorn
        certbot renew --quiet
        systemctl reload nginx
        EOF

        # Remove the private key for security
        rm /tmp/private_key
      env:
        SSH_PRIVATE_KEY: |
          -----BEGIN OPENSSH PRIVATE KEY-----
          AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBG4eWJ+ouG2bpGOO4mKKBANjjlh3suJngtZJzjpVTBu0ULSu0M5f+W9IPIxpUgOmFqLaklj/mNbVQB+DUisDrMI=
          -----END OPENSSH PRIVATE KEY-----