name: Deploy Django to DigitalOcean

on:
  push:
    branches:
      - master  # Replace with your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Match your Django version

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Deploy to DigitalOcean
      run: |
        sshpass -p "Hari2228@" ssh -o StrictHostKeyChecking=no root@139.59.88.123 << EOF
        echo "Connected to server"
        cd /home/CardsMaker
        git pull origin main
        source venv/bin/activate
        python manage.py migrate
        python manage.py collectstatic --noinput
        systemctl restart gunicorn
        certbot renew --quiet
        systemctl reload nginx
        EOF
      env:
        SSH_PRIVATE_KEY: |
          -----BEGIN OPENSSH PRIVATE KEY-----
          AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBG4eWJ+ouG2bpGOO4mKKBANjjlh3suJngtZJzjpVTBu0ULSu0M5f+W9IPIxpUgOmFqLaklj/mNbVQB+DUisDrMI=
          -----END OPENSSH PRIVATE KEY-----